/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tiago
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupPrincipal = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenuItem();
        sep1 = new javax.swing.JPopupMenu.Separator();
        menuNF = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelClientes = new javax.swing.JMenuItem();
        menuRelProdutos = new javax.swing.JMenu();
        menuRelProdutosCodigo = new javax.swing.JMenuItem();
        menuRelProdutosNome = new javax.swing.JMenuItem();
        menuRelProdutosEstoque = new javax.swing.JMenuItem();
        menuMovimento = new javax.swing.JMenu();
        menuInconsistencias = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuSairSistema = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");
        popupPrincipal.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        popupPrincipal.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        popupPrincipal.add(jMenuItem3);

        jMenuItem5.setText("jMenuItem5");
        jPopupMenu1.add(jMenuItem5);

        jMenuItem4.setText("jMenuItem4");
        jPopupMenu1.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa com Menus");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuCadastro.setText("Cadastro");

        menuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuClientes.setText("Clientes...");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menuClientes);

        menuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuProdutos.setText("Produtos...");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuProdutos);
        menuCadastro.add(sep1);

        menuNF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuNF.setText("Notas Fiscais...");
        menuNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNFActionPerformed(evt);
            }
        });
        menuCadastro.add(menuNF);

        barraMenu.add(menuCadastro);

        menuRelatorios.setText("Relatórios");

        menuRelClientes.setText("Relatório de Clientes...");
        menuRelatorios.add(menuRelClientes);

        menuRelProdutos.setText("Relatório de Produtos");

        menuRelProdutosCodigo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuRelProdutosCodigo.setText("Por Código...");
        menuRelProdutos.add(menuRelProdutosCodigo);

        menuRelProdutosNome.setText("Por Nome...");
        menuRelProdutos.add(menuRelProdutosNome);

        menuRelProdutosEstoque.setText("Por Estoque...");
        menuRelProdutos.add(menuRelProdutosEstoque);

        menuRelatorios.add(menuRelProdutos);

        barraMenu.add(menuRelatorios);

        menuMovimento.setText("Movimento");

        menuInconsistencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuInconsistencias.setText("Verificar Inconsistências...");
        menuMovimento.add(menuInconsistencias);

        barraMenu.add(menuMovimento);

        menuSair.setText("Sair");

        menuSairSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSairSistema.setText("Sair do Sistema");
        menuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairSistemaActionPerformed(evt);
            }
        });
        menuSair.add(menuSairSistema);

        barraMenu.add(menuSair);

        setJMenuBar(barraMenu);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairSistemaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairSistemaActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        // TODO add your handling code here:
        DialogClientes dc = new DialogClientes(this, true);
        dc.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //setComponentPopupMenu(popupPrincipal);

    }//GEN-LAST:event_formWindowOpened

    private void menuNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNFActionPerformed
        // TODO add your handling code here:
        DialogNotaFiscal nf = new DialogNotaFiscal(this, true);
        nf.setVisible(true);
    }//GEN-LAST:event_menuNFActionPerformed

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        // TODO add your handling code here:
        DialogProdutos dp = new DialogProdutos(this, true);
        dp.setVisible(true);
    }//GEN-LAST:event_menuProdutosActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuInconsistencias;
    private javax.swing.JMenu menuMovimento;
    private javax.swing.JMenuItem menuNF;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menuRelClientes;
    private javax.swing.JMenu menuRelProdutos;
    private javax.swing.JMenuItem menuRelProdutosCodigo;
    private javax.swing.JMenuItem menuRelProdutosEstoque;
    private javax.swing.JMenuItem menuRelProdutosNome;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSairSistema;
    private javax.swing.JPopupMenu popupPrincipal;
    private javax.swing.JPopupMenu.Separator sep1;
    // End of variables declaration//GEN-END:variables
}
